/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "Application",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Application__factory>;
    getContractFactory(
      name: "Constants",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Constants__factory>;
    getContractFactory(
      name: "Friends",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Friends__factory>;
    getContractFactory(
      name: "Message",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Message__factory>;
    getContractFactory(
      name: "Messenger",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Messenger__factory>;
    getContractFactory(
      name: "Token",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Token__factory>;

    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "Application",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Application>;
    getContractAt(
      name: "Constants",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Constants>;
    getContractAt(
      name: "Friends",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Friends>;
    getContractAt(
      name: "Message",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Message>;
    getContractAt(
      name: "Messenger",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Messenger>;
    getContractAt(
      name: "Token",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Token>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
